include(CTest)
option(MIRROR_OPENMP "Enable OpenMP if available" ON)
option(MIRROR_BUILD_CLASSIFIER "Build classification CLI" ON)
option(MIRROR_BUILD_OBJECT "Build detection CLI" ON)
option(MIRROR_BUILD_FACE "Build face detection CLI" ON)
option(MIRROR_BUILD_LEGACY "Build original face experiments" OFF)
set(DEMO_COMMON_DIR "${CMAKE_CURRENT_LIST_DIR}/../common")
find_package(OpenCV REQUIRED COMPONENTS core imgproc imgcodecs highgui)
if(MIRROR_OPENMP)
  find_package(OpenMP QUIET)
endif()
